import { ApplicationCommandOptionType, type RESTPostAPIApplicationGuildCommandsJSONBody } from "../../../types";

const data: RESTPostAPIApplicationGuildCommandsJSONBody = {
  name: "sensibo",
  description: "Control A/C via Sensibo",
  options: [
    {
      name: "actions",
      description: "Add/Edit/Remove Actions for Sensibo Pods",
      type: ApplicationCommandOptionType.SubcommandGroup,
      options: [
        {
          name: "add",
          description: "Add a new Action",
          type: ApplicationCommandOptionType.Subcommand,
          options: [
            {
              name: "pod",
              description: "Pod",
              type: ApplicationCommandOptionType.String,
              required: true,
              autocomplete: true,
            },
            {
              name: "enabled",
              description: "Enabled",
              type: ApplicationCommandOptionType.Boolean,
              required: true,
            },
            {
              name: "priority",
              description: "Priority",
              type: ApplicationCommandOptionType.Integer,
              required: true,
            },
            {
              name: "name",
              description: "Name",
              type: ApplicationCommandOptionType.String,
              required: true,
            },
            {
              name: "current_mode",
              description: "Current Mode?",
              type: ApplicationCommandOptionType.String,
              required: false,
              choices: [
                { name: "Off", value: "off" },
                { name: "Cool", value: "cool" },
                { name: "Dry", value: "dry" },
                { name: "Heat", value: "heat" },
                { name: "Fan", value: "fan" },
                { name: "Auto", value: "auto" },
              ],
            },
            {
              name: "room_temp_above",
              description: "Room Temp Above?",
              type: ApplicationCommandOptionType.Integer,
              required: false,
            },
            {
              name: "room_temp_below",
              description: "Room Temp Below?",
              type: ApplicationCommandOptionType.Integer,
              required: false,
            },
            {
              name: "outdoor_temp_above",
              description: "Outdoor Temp Above?",
              type: ApplicationCommandOptionType.Integer,
              required: false,
            },
            {
              name: "outdoor_temp_below",
              description: "Outdoor Temp Below?",
              type: ApplicationCommandOptionType.Integer,
              required: false,
            },
            {
              name: "time_hour_after",
              description: "Time Hour After?",
              type: ApplicationCommandOptionType.Integer,
              required: false,
            },
            {
              name: "time_hour_before",
              description: "Time Hour Before?",
              type: ApplicationCommandOptionType.Integer,
              required: false,
            },
            {
              name: "power",
              description: "Turn A/C On/Off?",
              type: ApplicationCommandOptionType.String,
              required: false,
              choices: [
                { name: "On", value: "on" },
                { name: "Off", value: "off" },
              ],
            },
            {
              name: "mode",
              description: "Set A/C Mode?",
              type: ApplicationCommandOptionType.String,
              required: false,
              choices: [
                { name: "Cool", value: "cool" },
                { name: "Dry", value: "dry" },
                { name: "Heat", value: "heat" },
                { name: "Fan", value: "fan" },
                { name: "Auto", value: "auto" },
              ],
            },
            {
              name: "fan_level",
              description: "Set Fan Level?",
              type: ApplicationCommandOptionType.String,
              required: false,
              choices: [
                { name: "Quiet", value: "quiet" },
                { name: "Low", value: "low" },
                { name: "Medium", value: "medium" },
                { name: "High", value: "high" },
                { name: "Strong", value: "strong" },
              ],
            },
            {
              name: "temperature",
              description: "Set Temperature?",
              type: ApplicationCommandOptionType.Integer,
              required: false,
              min_value: 62,
              max_value: 86,
            },
            {
              name: "swing_type",
              description: "Set Swing Type?",
              type: ApplicationCommandOptionType.String,
              required: false,
              choices: [
                { name: "Stopped (auto)", value: "stopped" },
                { name: "Moving", value: "rangeFull" },
              ],
            },
            {
              name: "light",
              description: "Turn Light On/Off?",
              type: ApplicationCommandOptionType.String,
              required: false,
              choices: [
                { name: "On", value: "on" },
                { name: "Off", value: "off" },
              ],
            },
          ],
        },
        {
          name: "clear",
          description: "Clear an action's settings",
          type: ApplicationCommandOptionType.Subcommand,
          options: [
            {
              name: "pod",
              description: "Pod",
              type: ApplicationCommandOptionType.String,
              required: true,
              autocomplete: true,
            },
            {
              name: "action",
              description: "Action",
              type: ApplicationCommandOptionType.String,
              required: true,
              autocomplete: true,
            },
            {
              name: "current_mode",
              description: "Clear Current Mode?",
              type: ApplicationCommandOptionType.Boolean,
              required: false,
            },
            {
              name: "room_temp_above",
              description: "Clear Room Temp Above?",
              type: ApplicationCommandOptionType.Boolean,
              required: false,
            },
            {
              name: "room_temp_below",
              description: "Clear Room Temp Below?",
              type: ApplicationCommandOptionType.Boolean,
              required: false,
            },
            {
              name: "outdoor_temp_above",
              description: "Clear Outdoor Temp Above?",
              type: ApplicationCommandOptionType.Boolean,
              required: false,
            },
            {
              name: "outdoor_temp_below",
              description: "Clear Outdoor Temp Below?",
              type: ApplicationCommandOptionType.Boolean,
              required: false,
            },
            {
              name: "time_hour_after",
              description: "Clear Time Hour After?",
              type: ApplicationCommandOptionType.Boolean,
              required: false,
            },
            {
              name: "time_hour_before",
              description: "Clear Time Hour Before?",
              type: ApplicationCommandOptionType.Boolean,
              required: false,
            },
            {
              name: "power",
              description: "Clear A/C Power State?",
              type: ApplicationCommandOptionType.Boolean,
              required: false,
            },
            {
              name: "mode",
              description: "Clear A/C Mode?",
              type: ApplicationCommandOptionType.Boolean,
              required: false,
            },
            {
              name: "fan_level",
              description: "Clear A/C Fan Level?",
              type: ApplicationCommandOptionType.Boolean,
              required: false,
            },
            {
              name: "temperature",
              description: "Clear A/C Temperature?",
              type: ApplicationCommandOptionType.Boolean,
              required: false,
            },
            {
              name: "swing_type",
              description: "Clear A/C Swing Type?",
              type: ApplicationCommandOptionType.Boolean,
              required: false,
            },
            {
              name: "light",
              description: "Clear A/C Light?",
              type: ApplicationCommandOptionType.Boolean,
              required: false,
            },
          ],
        },
        {
          name: "edit",
          description: "Edit an existing action",
          type: ApplicationCommandOptionType.Subcommand,
          options: [
            {
              name: "pod",
              description: "Pod",
              type: ApplicationCommandOptionType.String,
              required: true,
              autocomplete: true,
            },
            {
              name: "action",
              description: "Action",
              type: ApplicationCommandOptionType.String,
              required: true,
              autocomplete: true,
            },
            {
              name: "enabled",
              description: "Enabled?",
              type: ApplicationCommandOptionType.Boolean,
              required: false,
            },
            {
              name: "priority",
              description: "Priority?",
              type: ApplicationCommandOptionType.Integer,
              required: false,
            },
            {
              name: "title",
              description: "Title?",
              type: ApplicationCommandOptionType.String,
              required: false,
            },
            {
              name: "current_mode",
              description: "Current Mode?",
              type: ApplicationCommandOptionType.String,
              required: false,
              choices: [
                { name: "Off", value: "off" },
                { name: "Cool", value: "cool" },
                { name: "Dry", value: "dry" },
                { name: "Heat", value: "heat" },
                { name: "Fan", value: "fan" },
                { name: "Auto", value: "auto" },
              ],
            },
            {
              name: "room_temp_above",
              description: "Room Temp Above?",
              type: ApplicationCommandOptionType.Integer,
              required: false,
            },
            {
              name: "room_temp_below",
              description: "Room Temp Below?",
              type: ApplicationCommandOptionType.Integer,
              required: false,
            },
            {
              name: "outdoor_temp_above",
              description: "Outdoor Temp Above?",
              type: ApplicationCommandOptionType.Integer,
              required: false,
            },
            {
              name: "outdoor_temp_below",
              description: "Outdoor Temp Below",
              type: ApplicationCommandOptionType.Integer,
              required: false,
            },
            {
              name: "time_hour_after",
              description: "Time Hour After?",
              type: ApplicationCommandOptionType.Integer,
              required: false,
            },
            {
              name: "time_hour_before",
              description: "Time Hour Before?",
              type: ApplicationCommandOptionType.Integer,
              required: false,
            },
            {
              name: "power",
              description: "Turn A/C On/Off?",
              type: ApplicationCommandOptionType.String,
              required: false,
              choices: [
                { name: "On", value: "on" },
                { name: "Off", value: "off" },
              ],
            },
            {
              name: "mode",
              description: "Set A/C Mode?",
              type: ApplicationCommandOptionType.String,
              required: false,
              choices: [
                { name: "Cool", value: "cool" },
                { name: "Dry", value: "dry" },
                { name: "Heat", value: "heat" },
                { name: "Fan", value: "fan" },
                { name: "Auto", value: "auto" },
              ],
            },
            {
              name: "fan_level",
              description: "Set Fan Level?",
              type: ApplicationCommandOptionType.String,
              required: false,
              choices: [
                { name: "Quiet", value: "quiet" },
                { name: "Low", value: "low" },
                { name: "Medium", value: "medium" },
                { name: "High", value: "high" },
                { name: "Strong", value: "strong" },
              ],
            },
            {
              name: "temperature",
              description: "Set Temperature?",
              type: ApplicationCommandOptionType.Integer,
              required: false,
              min_value: 62,
              max_value: 86,
            },
            {
              name: "swing_type",
              description: "Set Swing Type?",
              type: ApplicationCommandOptionType.String,
              required: false,
              choices: [
                { name: "Stopped (auto)", value: "stopped" },
                { name: "Moving", value: "rangeFull" },
              ],
            },
            {
              name: "light",
              description: "Turn Light On/Off?",
              type: ApplicationCommandOptionType.String,
              required: false,
              choices: [
                { name: "On", value: "on" },
                { name: "Off", value: "off" },
              ],
            },
          ],
        },
        {
          name: "list",
          description: "List Action(s) for a Sensibo Pod",
          type: ApplicationCommandOptionType.Subcommand,
          options: [
            {
              name: "pod",
              description: "Pod",
              type: ApplicationCommandOptionType.String,
              required: true,
              autocomplete: true,
            },
            {
              name: "action",
              description: "Action",
              type: ApplicationCommandOptionType.String,
              required: false,
              autocomplete: true,
            },
          ],
        },
        {
          name: "remove",
          description: "Remove an Action from a Sensibo Pod",
          type: ApplicationCommandOptionType.Subcommand,
          options: [
            {
              name: "pod",
              description: "Pod",
              type: ApplicationCommandOptionType.String,
              required: true,
              autocomplete: true,
            },
            {
              name: "action",
              description: "Action",
              type: ApplicationCommandOptionType.String,
              required: true,
              autocomplete: true,
            },
          ],
        },
      ],
    },
    {
      name: "config",
      description: "Configure the Sensibo settings",
      type: ApplicationCommandOptionType.Subcommand,
      options: [
        {
          name: "cutoff_hour",
          description: "Cutoff Hour for singular Time Hour Before/After triggers",
          type: ApplicationCommandOptionType.Integer,
          required: false,
          min_value: 0,
          max_value: 24,
        },
      ],
    },
    {
      name: "pods",
      description: "Add or remove Sensibo Pods",
      type: ApplicationCommandOptionType.SubcommandGroup,
      options: [
        {
          name: "add",
          description: "Add a new Sensibo Pod",
          type: ApplicationCommandOptionType.Subcommand,
          options: [
            {
              name: "pod",
              description: "The Sensibo Pod to add from Sensibo's list of devices",
              type: ApplicationCommandOptionType.String,
              required: true,
              autocomplete: true,
            },
          ],
        },
        {
          name: "remove",
          description: "Remove an existing Sensibo Pod",
          type: ApplicationCommandOptionType.Subcommand,
          options: [
            {
              name: "pod",
              description: "The Sensibo Pod to remove",
              type: ApplicationCommandOptionType.String,
              required: true,
              autocomplete: true,
            },
          ],
        },
      ],
    },
    {
      name: "state",
      description: "Set the A/C State for the given Sensibo Pod",
      type: ApplicationCommandOptionType.Subcommand,
      options: [
        {
          name: "pod",
          description: "Which Sensibo Pod to adjust the state",
          type: ApplicationCommandOptionType.String,
          required: true,
          autocomplete: true,
        },
        {
          name: "power",
          description: "Whether the A/C is turned on or not",
          type: ApplicationCommandOptionType.String,
          required: false,
          choices: [
            { name: "On", value: "on" },
            { name: "Off", value: "off" },
          ],
        },
        {
          name: "mode",
          description: "The mode the A/C should operate in",
          type: ApplicationCommandOptionType.String,
          required: false,
          choices: [
            { name: "Cool", value: "cool" },
            { name: "Dry", value: "dry" },
            { name: "Heat", value: "heat" },
            { name: "Fan", value: "fan" },
            { name: "Auto", value: "auto" },
          ],
        },
        {
          name: "fan_level",
          description: "The fan speed the A/C should operate at",
          type: ApplicationCommandOptionType.String,
          required: false,
          choices: [
            { name: "Auto", value: "auto" },
            { name: "Quiet", value: "quiet" },
            { name: "Low", value: "low" },
            { name: "Medium", value: "medium" },
            { name: "High", value: "high" },
            { name: "Strong", value: "strong" },
          ],
        },
        {
          name: "temperature",
          description: "Temperature to set the A/C to",
          type: ApplicationCommandOptionType.Integer,
          required: false,
          min_value: 62,
          max_value: 86,
        },
        {
          name: "swing_type",
          description: "The type of swing behavior to use",
          type: ApplicationCommandOptionType.String,
          required: false,
          choices: [
            { name: "Stopped (auto)", value: "stopped" },
            { name: "Moving", value: "rangeFull" },
          ],
        },
        {
          name: "light",
          description: "Whether the lights on the A/C are turned on or not",
          type: ApplicationCommandOptionType.String,
          required: false,
          choices: [
            { name: "On", value: "on" },
            { name: "Off", value: "off" },
          ],
        },
      ],
    },
  ],
  default_member_permissions: "0",
};

export default data;
